# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from diff_drive_controller/WheelData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class WheelData(genpy.Message):
  _md5sum = "f3cef9a3c8f62c082f7316e75ecd5bc5"
  _type = "diff_drive_controller/WheelData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string[] left_wheel_joint_names
string[] right_wheel_joint_names

float64[] left_wheel_joint_actual_position
float64[] right_wheel_joint_actual_position

float64[] left_wheel_joint_actual_velocity
float64[] right_wheel_joint_actual_velocity

float64[] left_wheel_joint_reference_velocity
float64[] right_wheel_joint_reference_velocity
"""
  __slots__ = ['left_wheel_joint_names','right_wheel_joint_names','left_wheel_joint_actual_position','right_wheel_joint_actual_position','left_wheel_joint_actual_velocity','right_wheel_joint_actual_velocity','left_wheel_joint_reference_velocity','right_wheel_joint_reference_velocity']
  _slot_types = ['string[]','string[]','float64[]','float64[]','float64[]','float64[]','float64[]','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_wheel_joint_names,right_wheel_joint_names,left_wheel_joint_actual_position,right_wheel_joint_actual_position,left_wheel_joint_actual_velocity,right_wheel_joint_actual_velocity,left_wheel_joint_reference_velocity,right_wheel_joint_reference_velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WheelData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left_wheel_joint_names is None:
        self.left_wheel_joint_names = []
      if self.right_wheel_joint_names is None:
        self.right_wheel_joint_names = []
      if self.left_wheel_joint_actual_position is None:
        self.left_wheel_joint_actual_position = []
      if self.right_wheel_joint_actual_position is None:
        self.right_wheel_joint_actual_position = []
      if self.left_wheel_joint_actual_velocity is None:
        self.left_wheel_joint_actual_velocity = []
      if self.right_wheel_joint_actual_velocity is None:
        self.right_wheel_joint_actual_velocity = []
      if self.left_wheel_joint_reference_velocity is None:
        self.left_wheel_joint_reference_velocity = []
      if self.right_wheel_joint_reference_velocity is None:
        self.right_wheel_joint_reference_velocity = []
    else:
      self.left_wheel_joint_names = []
      self.right_wheel_joint_names = []
      self.left_wheel_joint_actual_position = []
      self.right_wheel_joint_actual_position = []
      self.left_wheel_joint_actual_velocity = []
      self.right_wheel_joint_actual_velocity = []
      self.left_wheel_joint_reference_velocity = []
      self.right_wheel_joint_reference_velocity = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.left_wheel_joint_names)
      buff.write(_struct_I.pack(length))
      for val1 in self.left_wheel_joint_names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *val1))
        else:
          buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.right_wheel_joint_names)
      buff.write(_struct_I.pack(length))
      for val1 in self.right_wheel_joint_names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *val1))
        else:
          buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.left_wheel_joint_actual_position)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.left_wheel_joint_actual_position))
      length = len(self.right_wheel_joint_actual_position)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.right_wheel_joint_actual_position))
      length = len(self.left_wheel_joint_actual_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.left_wheel_joint_actual_velocity))
      length = len(self.right_wheel_joint_actual_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.right_wheel_joint_actual_velocity))
      length = len(self.left_wheel_joint_reference_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.left_wheel_joint_reference_velocity))
      length = len(self.right_wheel_joint_reference_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.right_wheel_joint_reference_velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.left_wheel_joint_names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.left_wheel_joint_names.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.right_wheel_joint_names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.right_wheel_joint_names.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_wheel_joint_actual_position = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_wheel_joint_actual_position = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_wheel_joint_actual_velocity = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_wheel_joint_actual_velocity = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_wheel_joint_reference_velocity = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_wheel_joint_reference_velocity = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.left_wheel_joint_names)
      buff.write(_struct_I.pack(length))
      for val1 in self.left_wheel_joint_names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *val1))
        else:
          buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.right_wheel_joint_names)
      buff.write(_struct_I.pack(length))
      for val1 in self.right_wheel_joint_names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *val1))
        else:
          buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.left_wheel_joint_actual_position)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.left_wheel_joint_actual_position.tostring())
      length = len(self.right_wheel_joint_actual_position)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.right_wheel_joint_actual_position.tostring())
      length = len(self.left_wheel_joint_actual_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.left_wheel_joint_actual_velocity.tostring())
      length = len(self.right_wheel_joint_actual_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.right_wheel_joint_actual_velocity.tostring())
      length = len(self.left_wheel_joint_reference_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.left_wheel_joint_reference_velocity.tostring())
      length = len(self.right_wheel_joint_reference_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.right_wheel_joint_reference_velocity.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.left_wheel_joint_names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.left_wheel_joint_names.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.right_wheel_joint_names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.right_wheel_joint_names.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_wheel_joint_actual_position = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_wheel_joint_actual_position = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_wheel_joint_actual_velocity = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_wheel_joint_actual_velocity = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_wheel_joint_reference_velocity = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_wheel_joint_reference_velocity = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
