(cl:defpackage pal_interaction_msgs-srv
  (:use )
  (:export
   "RECOGNIZERSERVICE"
   "<RECOGNIZERSERVICE-REQUEST>"
   "RECOGNIZERSERVICE-REQUEST"
   "<RECOGNIZERSERVICE-RESPONSE>"
   "RECOGNIZERSERVICE-RESPONSE"
   "ASRSERVICE"
   "<ASRSERVICE-REQUEST>"
   "ASRSERVICE-REQUEST"
   "<ASRSERVICE-RESPONSE>"
   "ASRSERVICE-RESPONSE"
   "SOUNDLOCALISATIONSERVICE"
   "<SOUNDLOCALISATIONSERVICE-REQUEST>"
   "SOUNDLOCALISATIONSERVICE-REQUEST"
   "<SOUNDLOCALISATIONSERVICE-RESPONSE>"
   "SOUNDLOCALISATIONSERVICE-RESPONSE"
  ))

