(cl:in-package diff_drive_controller-msg)
(cl:export '(LEFT_WHEEL_JOINT_NAMES-VAL
          LEFT_WHEEL_JOINT_NAMES
          RIGHT_WHEEL_JOINT_NAMES-VAL
          RIGHT_WHEEL_JOINT_NAMES
          LEFT_WHEEL_JOINT_ACTUAL_POSITION-VAL
          LEFT_WHEEL_JOINT_ACTUAL_POSITION
          RIGHT_WHEEL_JOINT_ACTUAL_POSITION-VAL
          RIGHT_WHEEL_JOINT_ACTUAL_POSITION
          LEFT_WHEEL_JOINT_ACTUAL_VELOCITY-VAL
          LEFT_WHEEL_JOINT_ACTUAL_VELOCITY
          RIGHT_WHEEL_JOINT_ACTUAL_VELOCITY-VAL
          RIGHT_WHEEL_JOINT_ACTUAL_VELOCITY
          LEFT_WHEEL_JOINT_REFERENCE_VELOCITY-VAL
          LEFT_WHEEL_JOINT_REFERENCE_VELOCITY
          RIGHT_WHEEL_JOINT_REFERENCE_VELOCITY-VAL
          RIGHT_WHEEL_JOINT_REFERENCE_VELOCITY
))