(cl:defpackage pal_device_msgs-srv
  (:use )
  (:export
   "TIMEDCOLOUREFFECT"
   "<TIMEDCOLOUREFFECT-REQUEST>"
   "TIMEDCOLOUREFFECT-REQUEST"
   "<TIMEDCOLOUREFFECT-RESPONSE>"
   "TIMEDCOLOUREFFECT-RESPONSE"
   "TIMEDBLINKEFFECT"
   "<TIMEDBLINKEFFECT-REQUEST>"
   "TIMEDBLINKEFFECT-REQUEST"
   "<TIMEDBLINKEFFECT-RESPONSE>"
   "TIMEDBLINKEFFECT-RESPONSE"
   "CANCELEFFECT"
   "<CANCELEFFECT-REQUEST>"
   "CANCELEFFECT-REQUEST"
   "<CANCELEFFECT-RESPONSE>"
   "CANCELEFFECT-RESPONSE"
   "TIMEDFADEEFFECT"
   "<TIMEDFADEEFFECT-REQUEST>"
   "TIMEDFADEEFFECT-REQUEST"
   "<TIMEDFADEEFFECT-RESPONSE>"
   "TIMEDFADEEFFECT-RESPONSE"
  ))

