// Generated by gencpp from file diff_drive_controller/WheelDataStamped.msg
// DO NOT EDIT!


#ifndef DIFF_DRIVE_CONTROLLER_MESSAGE_WHEELDATASTAMPED_H
#define DIFF_DRIVE_CONTROLLER_MESSAGE_WHEELDATASTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <diff_drive_controller/WheelData.h>

namespace diff_drive_controller
{
template <class ContainerAllocator>
struct WheelDataStamped_
{
  typedef WheelDataStamped_<ContainerAllocator> Type;

  WheelDataStamped_()
    : header()
    , data()  {
    }
  WheelDataStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::diff_drive_controller::WheelData_<ContainerAllocator>  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> const> ConstPtr;

}; // struct WheelDataStamped_

typedef ::diff_drive_controller::WheelDataStamped_<std::allocator<void> > WheelDataStamped;

typedef boost::shared_ptr< ::diff_drive_controller::WheelDataStamped > WheelDataStampedPtr;
typedef boost::shared_ptr< ::diff_drive_controller::WheelDataStamped const> WheelDataStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace diff_drive_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'diff_drive_controller': ['/home/samuel/tiago_public_ws/src/ros_controllers/diff_drive_controller/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f39a7efcdb1d13b8233b4a91391d500";
  }

  static const char* value(const ::diff_drive_controller::WheelDataStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f39a7efcdb1d13bULL;
  static const uint64_t static_value2 = 0x8233b4a91391d500ULL;
};

template<class ContainerAllocator>
struct DataType< ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diff_drive_controller/WheelDataStamped";
  }

  static const char* value(const ::diff_drive_controller::WheelDataStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
WheelData data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: diff_drive_controller/WheelData\n\
string[] left_wheel_joint_names\n\
string[] right_wheel_joint_names\n\
\n\
float64[] left_wheel_joint_actual_position\n\
float64[] right_wheel_joint_actual_position\n\
\n\
float64[] left_wheel_joint_actual_velocity\n\
float64[] right_wheel_joint_actual_velocity\n\
\n\
float64[] left_wheel_joint_reference_velocity\n\
float64[] right_wheel_joint_reference_velocity\n\
";
  }

  static const char* value(const ::diff_drive_controller::WheelDataStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelDataStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diff_drive_controller::WheelDataStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diff_drive_controller::WheelDataStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    s << std::endl;
    Printer< ::diff_drive_controller::WheelData_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIFF_DRIVE_CONTROLLER_MESSAGE_WHEELDATASTAMPED_H
